name: 'warehouse'
version: '1.0.0'

profile: 'warehouse'

model-paths: ["warehouse/models"]
analysis-paths: ["warehouse/analyses"]
test-paths: ["warehouse/tests"]
seed-paths: ["warehouse/seeds"]
macro-paths: ["warehouse/macros"]
snapshot-paths: ["warehouse/snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "warehouse/target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  warehouse:
    # Config indicated by + and applies to all files under models/example/
    bronze:
      +materialized: table
