JSON_RESPONSE = {
    "location": {
        "name": "Liverpool",
        "region": "Merseyside",
        "country": "United Kingdom",
        "lat": 53.4166,
        "lon": -2.9418,
        "tz_id": "Europe/London",
        "localtime_epoch": 1747504626,
        "localtime": "2025-05-17 18:57",
    },
    "current": {
        "last_updated_epoch": 1747503900,
        "last_updated": "2025-05-17 18:45",
        "temp_c": 17.1,
        "temp_f": 62.8,
        "is_day": 1,
        "condition": {
            "text": "Sunny",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
            "code": 1000,
        },
        "wind_mph": 7.6,
        "wind_kph": 12.2,
        "wind_degree": 29,
        "wind_dir": "NNE",
        "pressure_mb": 1022.0,
        "pressure_in": 30.18,
        "precip_mm": 0.0,
        "precip_in": 0.0,
        "humidity": 55,
        "cloud": 25,
        "feelslike_c": 17.1,
        "feelslike_f": 62.8,
        "windchill_c": 17.8,
        "windchill_f": 64.1,
        "heatindex_c": 17.8,
        "heatindex_f": 64.1,
        "dewpoint_c": 8.1,
        "dewpoint_f": 46.5,
        "vis_km": 10.0,
        "vis_miles": 6.0,
        "uv": 1.3,
        "gust_mph": 11.4,
        "gust_kph": 18.3,
    },
    "forecast": {
        "forecastday": [
            {
                "date": "2025-05-17",
                "date_epoch": 1747440000,
                "day": {
                    "maxtemp_c": 18.8,
                    "maxtemp_f": 65.9,
                    "mintemp_c": 7.7,
                    "mintemp_f": 45.9,
                    "avgtemp_c": 13.2,
                    "avgtemp_f": 55.8,
                    "maxwind_mph": 9.8,
                    "maxwind_kph": 15.8,
                    "totalprecip_mm": 0.0,
                    "totalprecip_in": 0.0,
                    "totalsnow_cm": 0.0,
                    "avgvis_km": 10.0,
                    "avgvis_miles": 6.0,
                    "avghumidity": 64,
                    "daily_will_it_rain": 0,
                    "daily_chance_of_rain": 0,
                    "daily_will_it_snow": 0,
                    "daily_chance_of_snow": 0,
                    "condition": {
                        "text": "Sunny",
                        "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        "code": 1000,
                    },
                    "uv": 1.7,
                },
                "astro": {
                    "sunrise": "05:08 AM",
                    "sunset": "09:09 PM",
                    "moonrise": "01:37 AM",
                    "moonset": "07:59 AM",
                    "moon_phase": "Waning Gibbous",
                    "moon_illumination": 83,
                    "is_moon_up": 0,
                    "is_sun_up": 0,
                },
                "hour": [
                    {
                        "time_epoch": 1747436400,
                        "time": "2025-05-17 00:00",
                        "temp_c": 9.7,
                        "temp_f": 49.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.9,
                        "wind_kph": 7.9,
                        "wind_degree": 90,
                        "wind_dir": "E",
                        "pressure_mb": 1027.0,
                        "pressure_in": 30.32,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 79,
                        "cloud": 0,
                        "feelslike_c": 8.6,
                        "feelslike_f": 47.6,
                        "windchill_c": 8.6,
                        "windchill_f": 47.6,
                        "heatindex_c": 9.7,
                        "heatindex_f": 49.4,
                        "dewpoint_c": 6.2,
                        "dewpoint_f": 43.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.1,
                        "gust_kph": 14.7,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747440000,
                        "time": "2025-05-17 01:00",
                        "temp_c": 8.8,
                        "temp_f": 47.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 89,
                        "wind_dir": "E",
                        "pressure_mb": 1027.0,
                        "pressure_in": 30.32,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 83,
                        "cloud": 0,
                        "feelslike_c": 7.6,
                        "feelslike_f": 45.6,
                        "windchill_c": 7.6,
                        "windchill_f": 45.6,
                        "heatindex_c": 8.8,
                        "heatindex_f": 47.9,
                        "dewpoint_c": 6.1,
                        "dewpoint_f": 43.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.0,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747443600,
                        "time": "2025-05-17 02:00",
                        "temp_c": 8.3,
                        "temp_f": 47.0,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.7,
                        "wind_kph": 7.6,
                        "wind_degree": 80,
                        "wind_dir": "E",
                        "pressure_mb": 1027.0,
                        "pressure_in": 30.32,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 85,
                        "cloud": 0,
                        "feelslike_c": 7.1,
                        "feelslike_f": 44.8,
                        "windchill_c": 7.1,
                        "windchill_f": 44.8,
                        "heatindex_c": 8.3,
                        "heatindex_f": 47.0,
                        "dewpoint_c": 5.9,
                        "dewpoint_f": 42.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.5,
                        "gust_kph": 13.6,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747447200,
                        "time": "2025-05-17 03:00",
                        "temp_c": 8.1,
                        "temp_f": 46.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 5.1,
                        "wind_kph": 8.3,
                        "wind_degree": 86,
                        "wind_dir": "E",
                        "pressure_mb": 1026.0,
                        "pressure_in": 30.3,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 0,
                        "feelslike_c": 6.7,
                        "feelslike_f": 44.0,
                        "windchill_c": 6.7,
                        "windchill_f": 44.0,
                        "heatindex_c": 8.1,
                        "heatindex_f": 46.5,
                        "dewpoint_c": 5.4,
                        "dewpoint_f": 41.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.6,
                        "gust_kph": 15.4,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747450800,
                        "time": "2025-05-17 04:00",
                        "temp_c": 7.7,
                        "temp_f": 45.9,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 88,
                        "wind_dir": "E",
                        "pressure_mb": 1026.0,
                        "pressure_in": 30.29,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 84,
                        "cloud": 0,
                        "feelslike_c": 6.5,
                        "feelslike_f": 43.8,
                        "windchill_c": 6.5,
                        "windchill_f": 43.8,
                        "heatindex_c": 7.7,
                        "heatindex_f": 45.9,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.4,
                        "gust_kph": 13.5,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747454400,
                        "time": "2025-05-17 05:00",
                        "temp_c": 8.1,
                        "temp_f": 46.5,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.0,
                        "wind_kph": 6.5,
                        "wind_degree": 91,
                        "wind_dir": "E",
                        "pressure_mb": 1026.0,
                        "pressure_in": 30.29,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 83,
                        "cloud": 0,
                        "feelslike_c": 7.1,
                        "feelslike_f": 44.8,
                        "windchill_c": 7.1,
                        "windchill_f": 44.8,
                        "heatindex_c": 8.1,
                        "heatindex_f": 46.5,
                        "dewpoint_c": 5.3,
                        "dewpoint_f": 41.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.0,
                        "gust_kph": 11.3,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747458000,
                        "time": "2025-05-17 06:00",
                        "temp_c": 9.8,
                        "temp_f": 49.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 82,
                        "wind_dir": "E",
                        "pressure_mb": 1026.0,
                        "pressure_in": 30.29,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 76,
                        "cloud": 0,
                        "feelslike_c": 9.0,
                        "feelslike_f": 48.1,
                        "windchill_c": 9.0,
                        "windchill_f": 48.1,
                        "heatindex_c": 9.8,
                        "heatindex_f": 49.7,
                        "dewpoint_c": 5.7,
                        "dewpoint_f": 42.3,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.1,
                        "gust_kph": 9.9,
                        "uv": 0.1,
                    },
                    {
                        "time_epoch": 1747461600,
                        "time": "2025-05-17 07:00",
                        "temp_c": 11.4,
                        "temp_f": 52.5,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 67,
                        "wind_dir": "ENE",
                        "pressure_mb": 1026.0,
                        "pressure_in": 30.29,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 69,
                        "cloud": 9,
                        "feelslike_c": 10.4,
                        "feelslike_f": 50.7,
                        "windchill_c": 10.4,
                        "windchill_f": 50.7,
                        "heatindex_c": 11.4,
                        "heatindex_f": 52.5,
                        "dewpoint_c": 5.8,
                        "dewpoint_f": 42.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.1,
                        "gust_kph": 11.4,
                        "uv": 0.4,
                    },
                    {
                        "time_epoch": 1747465200,
                        "time": "2025-05-17 08:00",
                        "temp_c": 12.7,
                        "temp_f": 54.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003,
                        },
                        "wind_mph": 6.5,
                        "wind_kph": 10.4,
                        "wind_degree": 56,
                        "wind_dir": "ENE",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.28,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 64,
                        "cloud": 37,
                        "feelslike_c": 11.9,
                        "feelslike_f": 53.3,
                        "windchill_c": 11.9,
                        "windchill_f": 53.3,
                        "heatindex_c": 12.8,
                        "heatindex_f": 55.0,
                        "dewpoint_c": 6.2,
                        "dewpoint_f": 43.1,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 7.5,
                        "gust_kph": 12.0,
                        "uv": 1.0,
                    },
                    {
                        "time_epoch": 1747468800,
                        "time": "2025-05-17 09:00",
                        "temp_c": 13.3,
                        "temp_f": 55.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003,
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 54,
                        "wind_dir": "NE",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.28,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 62,
                        "cloud": 56,
                        "feelslike_c": 12.3,
                        "feelslike_f": 54.1,
                        "windchill_c": 12.3,
                        "windchill_f": 54.1,
                        "heatindex_c": 13.3,
                        "heatindex_f": 55.9,
                        "dewpoint_c": 6.2,
                        "dewpoint_f": 43.2,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.7,
                        "gust_kph": 14.1,
                        "uv": 1.9,
                    },
                    {
                        "time_epoch": 1747472400,
                        "time": "2025-05-17 10:00",
                        "temp_c": 14.1,
                        "temp_f": 57.4,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003,
                        },
                        "wind_mph": 8.7,
                        "wind_kph": 14.0,
                        "wind_degree": 52,
                        "wind_dir": "NE",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.28,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 60,
                        "cloud": 52,
                        "feelslike_c": 13.1,
                        "feelslike_f": 55.5,
                        "windchill_c": 13.1,
                        "windchill_f": 55.5,
                        "heatindex_c": 14.1,
                        "heatindex_f": 57.4,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.0,
                        "gust_kph": 16.2,
                        "uv": 3.2,
                    },
                    {
                        "time_epoch": 1747476000,
                        "time": "2025-05-17 11:00",
                        "temp_c": 15.1,
                        "temp_f": 59.2,
                        "is_day": 1,
                        "condition": {
                            "text": "Partly Cloudy ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            "code": 1003,
                        },
                        "wind_mph": 8.9,
                        "wind_kph": 14.4,
                        "wind_degree": 46,
                        "wind_dir": "NE",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.27,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 56,
                        "cloud": 31,
                        "feelslike_c": 15.1,
                        "feelslike_f": 59.2,
                        "windchill_c": 15.1,
                        "windchill_f": 59.2,
                        "heatindex_c": 15.1,
                        "heatindex_f": 59.2,
                        "dewpoint_c": 6.3,
                        "dewpoint_f": 43.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 10.3,
                        "gust_kph": 16.6,
                        "uv": 4.5,
                    },
                    {
                        "time_epoch": 1747479600,
                        "time": "2025-05-17 12:00",
                        "temp_c": 16.5,
                        "temp_f": 61.7,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 8.1,
                        "wind_kph": 13.0,
                        "wind_degree": 42,
                        "wind_dir": "NE",
                        "pressure_mb": 1025.0,
                        "pressure_in": 30.26,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 51,
                        "cloud": 2,
                        "feelslike_c": 16.5,
                        "feelslike_f": 61.7,
                        "windchill_c": 16.5,
                        "windchill_f": 61.7,
                        "heatindex_c": 16.5,
                        "heatindex_f": 61.7,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.3,
                        "gust_kph": 14.9,
                        "uv": 5.5,
                    },
                    {
                        "time_epoch": 1747483200,
                        "time": "2025-05-17 13:00",
                        "temp_c": 17.8,
                        "temp_f": 64.1,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 34,
                        "wind_dir": "NE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.24,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 48,
                        "cloud": 0,
                        "feelslike_c": 17.9,
                        "feelslike_f": 64.1,
                        "windchill_c": 17.9,
                        "windchill_f": 64.1,
                        "heatindex_c": 17.9,
                        "heatindex_f": 64.1,
                        "dewpoint_c": 6.6,
                        "dewpoint_f": 44.0,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.0,
                        "gust_kph": 12.9,
                        "uv": 5.9,
                    },
                    {
                        "time_epoch": 1747486800,
                        "time": "2025-05-17 14:00",
                        "temp_c": 18.8,
                        "temp_f": 65.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 7.2,
                        "wind_kph": 11.5,
                        "wind_degree": 8,
                        "wind_dir": "N",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 46,
                        "cloud": 0,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.8,
                        "windchill_c": 18.8,
                        "windchill_f": 65.8,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.8,
                        "dewpoint_c": 7.0,
                        "dewpoint_f": 44.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 8.2,
                        "gust_kph": 13.2,
                        "uv": 5.7,
                    },
                    {
                        "time_epoch": 1747490400,
                        "time": "2025-05-17 15:00",
                        "temp_c": 18.8,
                        "temp_f": 65.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 9.6,
                        "wind_kph": 15.5,
                        "wind_degree": 352,
                        "wind_dir": "N",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 48,
                        "cloud": 0,
                        "feelslike_c": 18.8,
                        "feelslike_f": 65.9,
                        "windchill_c": 18.8,
                        "windchill_f": 65.9,
                        "heatindex_c": 18.8,
                        "heatindex_f": 65.9,
                        "dewpoint_c": 7.7,
                        "dewpoint_f": 45.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.2,
                        "gust_kph": 18.0,
                        "uv": 4.9,
                    },
                    {
                        "time_epoch": 1747494000,
                        "time": "2025-05-17 16:00",
                        "temp_c": 18.5,
                        "temp_f": 65.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 9.8,
                        "wind_kph": 15.8,
                        "wind_degree": 354,
                        "wind_dir": "N",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 49,
                        "cloud": 0,
                        "feelslike_c": 18.5,
                        "feelslike_f": 65.2,
                        "windchill_c": 18.5,
                        "windchill_f": 65.2,
                        "heatindex_c": 18.5,
                        "heatindex_f": 65.2,
                        "dewpoint_c": 7.7,
                        "dewpoint_f": 45.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.3,
                        "gust_kph": 19.7,
                        "uv": 3.7,
                    },
                    {
                        "time_epoch": 1747497600,
                        "time": "2025-05-17 17:00",
                        "temp_c": 18.3,
                        "temp_f": 64.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 8.3,
                        "wind_kph": 13.3,
                        "wind_degree": 10,
                        "wind_dir": "N",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.2,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 50,
                        "cloud": 0,
                        "feelslike_c": 18.3,
                        "feelslike_f": 64.9,
                        "windchill_c": 18.3,
                        "windchill_f": 64.9,
                        "heatindex_c": 18.3,
                        "heatindex_f": 64.9,
                        "dewpoint_c": 7.7,
                        "dewpoint_f": 45.9,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.1,
                        "gust_kph": 17.8,
                        "uv": 2.4,
                    },
                    {
                        "time_epoch": 1747501200,
                        "time": "2025-05-17 18:00",
                        "temp_c": 17.1,
                        "temp_f": 62.8,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 7.6,
                        "wind_kph": 12.2,
                        "wind_degree": 29,
                        "wind_dir": "NNE",
                        "pressure_mb": 1022.0,
                        "pressure_in": 30.18,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 55,
                        "cloud": 25,
                        "feelslike_c": 17.8,
                        "feelslike_f": 64.1,
                        "windchill_c": 17.8,
                        "windchill_f": 64.1,
                        "heatindex_c": 17.8,
                        "heatindex_f": 64.1,
                        "dewpoint_c": 8.1,
                        "dewpoint_f": 46.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.4,
                        "gust_kph": 18.3,
                        "uv": 1.3,
                    },
                    {
                        "time_epoch": 1747504800,
                        "time": "2025-05-17 19:00",
                        "temp_c": 16.1,
                        "temp_f": 61.0,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 6.9,
                        "wind_kph": 11.2,
                        "wind_degree": 41,
                        "wind_dir": "NE",
                        "pressure_mb": 1023.0,
                        "pressure_in": 30.21,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 57,
                        "cloud": 7,
                        "feelslike_c": 16.1,
                        "feelslike_f": 61.0,
                        "windchill_c": 16.1,
                        "windchill_f": 61.0,
                        "heatindex_c": 16.1,
                        "heatindex_f": 61.0,
                        "dewpoint_c": 7.6,
                        "dewpoint_f": 45.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 12.1,
                        "gust_kph": 19.4,
                        "uv": 0.6,
                    },
                    {
                        "time_epoch": 1747508400,
                        "time": "2025-05-17 20:00",
                        "temp_c": 13.8,
                        "temp_f": 56.9,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 5.8,
                        "wind_kph": 9.4,
                        "wind_degree": 52,
                        "wind_dir": "NE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.22,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 61,
                        "cloud": 6,
                        "feelslike_c": 13.3,
                        "feelslike_f": 55.9,
                        "windchill_c": 13.3,
                        "windchill_f": 55.9,
                        "heatindex_c": 13.8,
                        "heatindex_f": 56.9,
                        "dewpoint_c": 6.4,
                        "dewpoint_f": 43.6,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 11.9,
                        "gust_kph": 19.2,
                        "uv": 0.2,
                    },
                    {
                        "time_epoch": 1747512000,
                        "time": "2025-05-17 21:00",
                        "temp_c": 12.4,
                        "temp_f": 54.3,
                        "is_day": 1,
                        "condition": {
                            "text": "Sunny",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 4.5,
                        "wind_kph": 7.2,
                        "wind_degree": 59,
                        "wind_dir": "ENE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.24,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 64,
                        "cloud": 5,
                        "feelslike_c": 12.0,
                        "feelslike_f": 53.5,
                        "windchill_c": 12.0,
                        "windchill_f": 53.5,
                        "heatindex_c": 12.4,
                        "heatindex_f": 54.3,
                        "dewpoint_c": 5.8,
                        "dewpoint_f": 42.5,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 9.4,
                        "gust_kph": 15.1,
                        "uv": 0.0,
                    },
                    {
                        "time_epoch": 1747515600,
                        "time": "2025-05-17 22:00",
                        "temp_c": 11.4,
                        "temp_f": 52.4,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 2.9,
                        "wind_kph": 4.7,
                        "wind_degree": 61,
                        "wind_dir": "ENE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.24,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 67,
                        "cloud": 4,
                        "feelslike_c": 11.4,
                        "feelslike_f": 52.5,
                        "windchill_c": 11.4,
                        "windchill_f": 52.5,
                        "heatindex_c": 11.4,
                        "heatindex_f": 52.4,
                        "dewpoint_c": 5.4,
                        "dewpoint_f": 41.8,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 6.1,
                        "gust_kph": 9.8,
                        "uv": 0,
                    },
                    {
                        "time_epoch": 1747519200,
                        "time": "2025-05-17 23:00",
                        "temp_c": 10.7,
                        "temp_f": 51.2,
                        "is_day": 0,
                        "condition": {
                            "text": "Clear ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            "code": 1000,
                        },
                        "wind_mph": 2.0,
                        "wind_kph": 3.2,
                        "wind_degree": 52,
                        "wind_dir": "NE",
                        "pressure_mb": 1024.0,
                        "pressure_in": 30.24,
                        "precip_mm": 0.0,
                        "precip_in": 0.0,
                        "snow_cm": 0.0,
                        "humidity": 69,
                        "cloud": 5,
                        "feelslike_c": 11.2,
                        "feelslike_f": 52.1,
                        "windchill_c": 11.2,
                        "windchill_f": 52.1,
                        "heatindex_c": 10.7,
                        "heatindex_f": 51.2,
                        "dewpoint_c": 5.2,
                        "dewpoint_f": 41.4,
                        "will_it_rain": 0,
                        "chance_of_rain": 0,
                        "will_it_snow": 0,
                        "chance_of_snow": 0,
                        "vis_km": 10.0,
                        "vis_miles": 6.0,
                        "gust_mph": 4.2,
                        "gust_kph": 6.8,
                        "uv": 0,
                    },
                ],
            },
        ],
    },
}
