version: 2
models:
- name: location_hourly_averages
  columns:
  - name: hour
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 23
          inclusive: true
  - name: location
    tests:
    - accepted_values:
        arguments:
          values:
          - liverpool
          - Liverpool
  - name: temp_c
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: -20
          max_value: 60
          inclusive: true
  - name: wind_kph
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: gust_kph
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: wind_degree
    tests: []
  - name: precip_mm
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: chance_of_rain
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 100
          inclusive: true
  - name: snow_cm
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: chance_of_snow
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 100
          inclusive: true
  - name: humidity
    tests: []
  - name: cloud
    tests: []
  - name: feelslike_c
    tests: []
  - name: windchill_c
    tests: []
  - name: heatindex_c
    tests: []
  - name: dewpoint_c
    tests: []
  - name: vis_km
    tests: []
- name: location_monthly_averages
  columns:
  - name: month
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 1
          max_value: 12
          inclusive: true
  - name: location
    tests:
    - accepted_values:
        arguments:
          values:
          - liverpool
          - Liverpool
  - name: temp_c
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: -20
          max_value: 60
          inclusive: true
  - name: wind_kph
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: gust_kph
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: wind_degree
    tests: []
  - name: precip_mm
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: chance_of_rain
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 100
          inclusive: true
  - name: snow_cm
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 120
          inclusive: true
  - name: chance_of_snow
    tests:
    - dbt_utils.accepted_range:
        arguments:
          min_value: 0
          max_value: 100
          inclusive: true
  - name: humidity
    tests: []
  - name: cloud
    tests: []
  - name: feelslike_c
    tests: []
  - name: windchill_c
    tests: []
  - name: heatindex_c
    tests: []
  - name: dewpoint_c
    tests: []
  - name: vis_km
    tests: []
