name: Run raw layer

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 1 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      
      - name: run at 1am UTC
        run: python ./src/weather_pipe/000_raw_pipe.py --config-path ./configs/raw_layer.yaml --api-key ${{ secrets.WEATHER_API_KEY }}

      - name: GIT commit and push data
        env: 
          CI_COMMIT_MESSAGE: "run: raw layer"
          CI_COMMIT_AUTHOR: pipe_job
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add data
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push