name: Run combine parquet

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 1 * *'

jobs:
  raw_layer:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync

      - name: run at 2am UTC 1st of each month
        run: |
          git status
          git pull origin main
          uv run "./src/weather_pipe/script_000_combine_parquets.py" --load-path "./data/raw/liverpool/*_forecast_liverpool.parquet" --save-dir "./data/combined_raw/liverpool"

      - name: Checkout branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: commit and push data
        env:
          CI_COMMIT_MESSAGE: "chore: combine parquets"
          CI_COMMIT_AUTHOR: cleanup_job
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git status
          git add data
          if ! git diff --cached --quiet; then
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          else
            echo "No changes to commit"
          fi
